modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/psych-ward/Sisser/issues"
license="MIT"

[[mods]]

modId="sisser"
version="${file.jarVersion}"
displayName="Sisser"

displayURL="https://github.com/psych-ward/Sisser" #optional
logoFile="sisser_logo.png"
credits="Thanks to the forge crew!"
authors="DanteChaos / DanteHelros"
description='''
Went off with a Sisser, it is a dutch saying when something that goes off but does nothing.

This mod prevent's a creepers explosion from damaging the surrounding area. It stil hurt's the player, TNT and other explosions also stil work as intended
'''

[[dependencies.sisser]] #optional

    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sisser]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
